[package]
name = "cellular_automata"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.31.0"
boolvec = "0.2.6"
rand = "0.8.4"
nalgebra-glm = "0.15.0"